---
version: "3"
services:
 devopsdb:
   image: pavan94913/mynewapp:dbimage
   ports:
     - "3306:3306"

 application:
   image: pavan94913/mynewapp:appimage
   container_name: containerapp
   ports:
     - "1111:8080"
   depends_on:
     - "devopsdb"
